import React from 'react'
import VideoCard from '../VideoCard/VideoCard'
import './RecommendedVideos.css'

function RecommendedVideos() {
    return (
        <div className='recommendedVideos'>
            <h2>Recommended</h2>
            <div className="recommendedVideos__videos">
                <VideoCard title='First Strike Finals' channel='Valorant' views='93K views' timestamp='3 hours ago' image='https://i.ytimg.com/vi/Rux0HjzKQbw/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAKF547oYfxwm9VJQLJPL6zgikMbQ' channelImage='https://files.cults3d.com/uploaders/15024335/illustration-file/a86d53e4-2bd9-4a8f-9550-986686c3131a/gi0mAjIh_400x400_large.png'/>
                <VideoCard title='The Most Intense Ending In PUBG' channel='Shroud' views='1.1M views' timestamp='1 day ago' image='https://i.ytimg.com/vi/v9pN5CgIphw/hqdefault.jpg?sqp=-oaymwEZCOADEI4CSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDxXD4ozCGm2Fzz-_E3U3bOL_eC1Q'channelImage='https://yt3.ggpht.com/ytc/AAUvwnhAtpHA0B2-10Xf0mDysSHFz6MI53IWjgsGCFAi1w=s176-c-k-c0x00ffffff-no-rj-mo'/>
                <VideoCard title='he tried to protect me with 7900IQ sacrifice' channel='Disguised Toast' views='2.9M views' timestamp='1 day ago' image='https://i.ytimg.com/vi/sEbYc3S26sk/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDV-33I0Nwe1rDatibaeMeWCfALhQ' channelImage='https://pbs.twimg.com/profile_images/711015457134813188/7Qcunhqi.jpg'/>
                <VideoCard title='First Strike Finals' channel='Valorant' views='93K views' timestamp='3 hours ago' image='https://i.ytimg.com/vi/Rux0HjzKQbw/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAKF547oYfxwm9VJQLJPL6zgikMbQ' channelImage='https://files.cults3d.com/uploaders/15024335/illustration-file/a86d53e4-2bd9-4a8f-9550-986686c3131a/gi0mAjIh_400x400_large.png'/>
                <VideoCard title='The Most Intense Ending In PUBG' channel='Shroud' views='1.1M views' timestamp='1 day ago' image='https://i.ytimg.com/vi/v9pN5CgIphw/hqdefault.jpg?sqp=-oaymwEZCOADEI4CSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDxXD4ozCGm2Fzz-_E3U3bOL_eC1Q'channelImage='https://yt3.ggpht.com/ytc/AAUvwnhAtpHA0B2-10Xf0mDysSHFz6MI53IWjgsGCFAi1w=s176-c-k-c0x00ffffff-no-rj-mo'/>
                <VideoCard title='he tried to protect me with 7900IQ sacrifice' channel='Disguised Toast' views='2.9M views' timestamp='1 day ago' image='https://i.ytimg.com/vi/sEbYc3S26sk/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDV-33I0Nwe1rDatibaeMeWCfALhQ' channelImage='https://pbs.twimg.com/profile_images/711015457134813188/7Qcunhqi.jpg'/><VideoCard title='First Strike Finals' channel='Valorant' views='93K views' timestamp='3 hours ago' image='https://i.ytimg.com/vi/Rux0HjzKQbw/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAKF547oYfxwm9VJQLJPL6zgikMbQ' channelImage='https://files.cults3d.com/uploaders/15024335/illustration-file/a86d53e4-2bd9-4a8f-9550-986686c3131a/gi0mAjIh_400x400_large.png'/>
                <VideoCard title='The Most Intense Ending In PUBG' channel='Shroud' views='1.1M views' timestamp='1 day ago' image='https://i.ytimg.com/vi/v9pN5CgIphw/hqdefault.jpg?sqp=-oaymwEZCOADEI4CSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDxXD4ozCGm2Fzz-_E3U3bOL_eC1Q'channelImage='https://yt3.ggpht.com/ytc/AAUvwnhAtpHA0B2-10Xf0mDysSHFz6MI53IWjgsGCFAi1w=s176-c-k-c0x00ffffff-no-rj-mo'/>
                <VideoCard title='he tried to protect me with 7900IQ sacrifice' channel='Disguised Toast' views='2.9M views' timestamp='1 day ago' image='https://i.ytimg.com/vi/sEbYc3S26sk/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDV-33I0Nwe1rDatibaeMeWCfALhQ' channelImage='https://pbs.twimg.com/profile_images/711015457134813188/7Qcunhqi.jpg'/><VideoCard title='First Strike Finals' channel='Valorant' views='93K views' timestamp='3 hours ago' image='https://i.ytimg.com/vi/Rux0HjzKQbw/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAKF547oYfxwm9VJQLJPL6zgikMbQ' channelImage='https://files.cults3d.com/uploaders/15024335/illustration-file/a86d53e4-2bd9-4a8f-9550-986686c3131a/gi0mAjIh_400x400_large.png'/>
                <VideoCard title='The Most Intense Ending In PUBG' channel='Shroud' views='1.1M views' timestamp='1 day ago' image='https://i.ytimg.com/vi/v9pN5CgIphw/hqdefault.jpg?sqp=-oaymwEZCOADEI4CSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDxXD4ozCGm2Fzz-_E3U3bOL_eC1Q'channelImage='https://yt3.ggpht.com/ytc/AAUvwnhAtpHA0B2-10Xf0mDysSHFz6MI53IWjgsGCFAi1w=s176-c-k-c0x00ffffff-no-rj-mo'/>
                <VideoCard title='he tried to protect me with 7900IQ sacrifice' channel='Disguised Toast' views='2.9M views' timestamp='1 day ago' image='https://i.ytimg.com/vi/sEbYc3S26sk/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDV-33I0Nwe1rDatibaeMeWCfALhQ' channelImage='https://pbs.twimg.com/profile_images/711015457134813188/7Qcunhqi.jpg'/><VideoCard title='First Strike Finals' channel='Valorant' views='93K views' timestamp='3 hours ago' image='https://i.ytimg.com/vi/Rux0HjzKQbw/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAKF547oYfxwm9VJQLJPL6zgikMbQ' channelImage='https://files.cults3d.com/uploaders/15024335/illustration-file/a86d53e4-2bd9-4a8f-9550-986686c3131a/gi0mAjIh_400x400_large.png'/>
                <VideoCard title='The Most Intense Ending In PUBG' channel='Shroud' views='1.1M views' timestamp='1 day ago' image='https://i.ytimg.com/vi/v9pN5CgIphw/hqdefault.jpg?sqp=-oaymwEZCOADEI4CSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDxXD4ozCGm2Fzz-_E3U3bOL_eC1Q'channelImage='https://yt3.ggpht.com/ytc/AAUvwnhAtpHA0B2-10Xf0mDysSHFz6MI53IWjgsGCFAi1w=s176-c-k-c0x00ffffff-no-rj-mo'/>
                <VideoCard title='he tried to protect me with 7900IQ sacrifice' channel='Disguised Toast' views='2.9M views' timestamp='1 day ago' image='https://i.ytimg.com/vi/sEbYc3S26sk/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDV-33I0Nwe1rDatibaeMeWCfALhQ' channelImage='https://pbs.twimg.com/profile_images/711015457134813188/7Qcunhqi.jpg'/>
            </div>
        </div>
    )
}

export default RecommendedVideos
